apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-serving-service
spec:
  replicas: 1
  selector:
    matchLabels: { app: iris-serving-service }
  template:
    metadata:
      labels: { app: iris-serving-service }
    spec:
      # ⚠️ 중요: EKS에서 S3에 접근할 수 있게 해주는 권한 설정입니다. (나중에 생성 필요)
      serviceAccountName: sagemaker-s3-access-sa
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: iris-serving-app
        image: ghcr.io/kinggodchan/iris-serving-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-s3-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-s3-credentials
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: aws-s3-credentials
              key: AWS_DEFAULT_REGION
---
apiVersion: v1
kind: Service
metadata:
  name: iris-serving-service
spec:
  selector: { app: iris-serving-service }
  ports:
  - port: 8080
    targetPort: 8080
