apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-service
spec:
  replicas: 1
  selector:
    matchLabels: { app: board-service }
  template:
    metadata:
      labels: { app: board-service }
    spec:
      containers:
      - name: board-app
        # 1. 태그를 :latest로 고정하여 CI(GitHub Actions)와 일치시킵니다.
        image: ghcr.io/kinggodchan/auth-service:latest
        # 2. ArgoCD가 새 이미지를 즉시 감지하고 내려받도록 설정합니다.
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "mysql"
        - name: DB_USER
          value: "test01"
        - name: DB_PASSWORD
          value: "P@ssw0rd"
        - name: DB_NAME
          value: "fastapi_db"
---
apiVersion: v1
kind: Service
metadata:
  name: board-service
spec:
  selector: { app: board-service }
  ports:
  - port: 8000
    targetPort: 8000
